spring:
  application:
    name: XYZ Movie booking
  datasource:
    url: jdbc:h2:mem:xyz-movie-booking-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      console.path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  #security:
   # basic:
    #  enabled: true
      #authorize-mode: NONE
